# Generated by Django 4.2 on 2023-08-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='owner',
            new_name='author',
        ),
    ]
