# Generated by Django 4.2 on 2023-08-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow_follow_unique_name_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_name_follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='blog',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'blog'), name='unique_name_follow'),
        ),
    ]
