# Generated by Django 4.2 on 2023-08-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_is_read_by_user'),
        ('users', '0006_remove_follow_unique_name_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_posts',
            field=models.ManyToManyField(blank=True, related_name='read_by', to='blog.post'),
        ),
    ]
