# Generated by Django 4.2 on 2023-08-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_read_by_user',
        ),
    ]
